### PR TITLE
Multiple outers

### LINKED ISSUE #399: Evaluation involving outer when there are multiple outer
I did not try but I suspect this evaluation to fail

```scala
class A(x: String) {
  class AInner {
    def xx: String = {
      x
    }
  }
}

class B(x: String, y: String) extends A(x) {
  class BInner extends AInner {
    def yy: String = {
      y // evaluate x or y
    }
  }
}
```

Because class `BInner` has two outers, one of type `A` and another of type `B`.

### PR DESCRIPTION
**Pull request by iusildra**
Fixes #399

### CODE REVIEW

File: modules/tests/src/main/scala/ch/epfl/scala/debugadapter/testfmk/TestingLoggers.scala [hunk 1]
```diff
@@ -14,9 +14,9 @@ object NoopLogger extends Logger {
...
  */
 object PrintLogger extends Logger {
-  override def debug(msg: => String): Unit = println(s"[DEBUG] $msg")
-  override def info(msg: => String): Unit = println(s"[INFO] $msg")
-  override def warn(msg: => String): Unit = println(s"[WARN] $msg")
-  override def error(msg: => String): Unit = System.err.println(s"[ERROR] $msg")
+  override def debug(msg: => String): Unit = println(s"\u001b[33m[DEBUG] ${msg}\u001b[0m")
+  override def info(msg: => String): Unit = println(s"\u001b[36m[INFO] ${msg}\u001b[0m")
+  override def warn(msg: => String): Unit = println(s"\u001b[91m[WARN] ${msg}\u001b[0m")
+  override def error(msg: => String): Unit = System.err.println(s"\u001b[31m[ERROR] ${msg}\u001b[0m")
```
Comment (adpi2) [inline modules/tests/src/main/scala/ch/epfl/scala/debugadapter/testfmk/TestingLoggers.scala:20]: I would prefer if you use the available `Console.RED` and `Console.RESET` constants instead of the ANSI codes.

Comment (iusildra) [reply modules/tests/src/main/scala/ch/epfl/scala/debugadapter/testfmk/TestingLoggers.scala:20]: Oops

**Comment by iusildra** [comment]
It should now be easier to fix #496

**Review by adpi2 — APPROVED** [review]
LGTM
