### PR TITLE
Log exceptions

### LINKED ISSUE #480: Log exceptions
## Description
As stated in [this pr review](https://github.com/scalacenter/scala-debug-adapter/pull/466), some exceptions must stop the evaluation and not fallback to the compiler (`VMDisconnectedException`...).
I switched back from returning a `Fatal` on exception to `CompilerRecoverable` after encountering some cases where it blocked the compiler from evaluating valid expressions. However, some exeptions are `Fatal` in any case and should stop the evaluation

## Objectives

```[tasklist]
- [x] Identify 'fatal' exceptions
- [ ] Stop evaluation on fatal ones,
- [ ] Continue evaluation with compiler for others, but log them to be able to correct them later
```

### PR DESCRIPTION
**Pull request by iusildra**
Fixes #480 

For now it simply print in the tests when an exceptions is thrown. Ideally it should be printed by a Logger, but I need to find a way to do so without having to pass it each time a `Validation` is instantiated

### CODE REVIEW

File: modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/evaluator/Validation.scala [hunk 1]
```diff
@@ -64,62 +72,73 @@ sealed abstract class Invalid(val exception: Exception) extends Validation[Nothi
...
+    extends Unrecoverable(exception)
 
 object Validation {
-  def apply[A](input: => A): Validation[A] = {
+  private def handler(t: Throwable)(implicit logger: Logger): Invalid = t match {
+    case e @ (_: VMDisconnectedException | _: ObjectCollectedException) => Fatal(e)
+    case e @ (_: InvalidStackFrameException | _: AbsentInformationException) => Fatal(e)
+    case e @ (_: InvocationException | _: VMOutOfMemoryException) => Fatal(e)
+    case e: Exception =>
+      println(s"\u001b[35mUnexpected error while validating: ${e}\u001b[0m")
```
Comment (adpi2) [inline modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/evaluator/Validation.scala:94]: Why don't you use the logger here?

File: modules/java-debug
Comment (adpi2) [inline modules/java-debug:1]: Do you know why there is an update of `java-debug` here? It's weird because it says that it contains 0 updated files.

File: modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/evaluator/Validation.scala (hunk 1 above)
Comment (iusildra) [reply modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/evaluator/Validation.scala:94]: Forgot to change it

File: modules/java-debug
Comment (iusildra) [reply modules/java-debug:1]: Yes, it's the merge commit (the previous version was the one on my branch)

File: modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/evaluator/Validation.scala [hunk 2]
```diff
@@ -33,7 +41,7 @@ sealed abstract class Validation[+A] {
   def toTry: Try[A]
 }
 
-final case class Valid[+A](value: A) extends Validation[A]() {
+final case class Valid[+A](value: A)(implicit logger: Logger) extends Validation[A]() {
```
[the remark this answers is not in the document]
Comment (iusildra) [reply modules/core/src/main/scala/ch/epfl/scala/debugadapter/internal/evaluator/Validation.scala]: I thought too, but passing it as implicit params in `map`/`flatMap` reduces the implicit parameters count

**Review by adpi2 — APPROVED** [review]
LGTM
